{% set python_min = "3.10" %}
{% set name = "txl-file-browser" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_file_browser-{{ version }}.tar.gz
  sha256: add92a385c2a0a1165cb23f015315c5c73b2403f130dc3963934064a261b5878

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_file_browser

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/file_browser
  summary: TXL plugin for a file browser
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/file_browser
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
