{% set name = "txl-file-browser" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_file_browser-{{ version }}.tar.gz
  sha256: 8b16efce9f5dd105f3a3572e28f26e3476d22c01afc1f62d17833ec0d3492eb3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_file_browser

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/file_browser
  summary: TXL plugin for a file browser
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/file_browser
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
