{% set python_min = "3.10" %}
{% set name = "txl-file-browser" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_file_browser-{{ version }}.tar.gz
  sha256: 93818429f73835466d62c69fdbaa80e69bd679446aefa2ba6cbb10342e8055f8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_file_browser

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/file_browser
  summary: TXL plugin for a file browser
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/file_browser
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
